name: innoq
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^5.0.4
  dio: ^5.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  flutter_bloc: ^8.1.1
  basic_utils: ^5.4.2
  modal_bottom_sheet: 
    git: 
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: 3e8c3682be91a4a86ee73f39606901d5eb033f0b
      path: modal_bottom_sheet
  shared_preferences: ^2.0.17
  intl: ^0.18.0
  visibility_detector: ^0.3.3
  collection: ^1.17.0
  qr_flutter: ^4.0.0
  flutter_color: ^2.0.0
  shimmer_animation: ^2.1.0+1
  screenshot: ^1.3.0
  share_plus: ^6.3.2
  qr_code_scanner: ^1.0.1
  pin_code_fields: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  injectable_generator: ^2.1.3

  dart_code_metrics: ^5.6.0

flutter:
  uses-material-design: true
